# configure these properties while deploying the application in AWS

cloud:
  aws:
    s3:
      bucket: agripulse-images
      endpoint: https://s3.amazonaws.com
    region: us-east-1
    credentials:
      access-key: <YOUR_AWS_ACCESS_KEY>
      secret-key: <YOUR_AWS_SECRET_KEY>